# Generated by Django 3.2.5 on 2021-07-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
