# Generated by Django 3.2.5 on 2021-07-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210719_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='category',
        ),
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.categories'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=150),
        ),
    ]
